---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  image: ubuntu-upstart:14.04
  run_command: /sbin/init

provisioner:
  name: chef_zero
  product_name: chef
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: app
    run_list:
      - recipe[choonz-queue-service::app]
    verifier:
      inspec_tests:
        - test/smoke/app
    driver_config:
      instance_name: cqs-app
  - name: zookeeper
    run_list:
      - recipe[choonz-queue-service::zookeeper]
    verifier:
      inspec_tests:
        - test/smoke/zookeeper
    driver_config:
      instance_name: cqs-zookeeper
  - name: kafka
    run_list:
      - recipe[choonz-queue-service::kafka]
    verifier:
      inspec_tests:
        - test/smoke/kafka
    driver_config:
      links: cqs-zookeeper:zookeeper
      instance_name: cqs-kafka
