---
transport:
  username: kitchen
  
driver:
  name: docker
  privileged: true
  use_sudo: false
  use_latest_docker: true

provisioner:
  name: chef_zero
  product_name: chef
  always_update_cookbooks: true

verifier:
  name: inspec
  sudo: false

platforms:
  - name: centos
    driver_config:
      dockerfile: dockerfiles/centos7
      platform: centos
      run_command: /usr/sbin/init
    attributes:
      is_docker: true
      host_uid: <%= `id -u` %>
      host_gid: <%= `id -g` %>
      CI: <%= ENV["CI"] %>

suites:
  - name: app
    run_list:
      - recipe[choonz-queue-service::app]
    driver_config:
      instance_name: cqs-app
  # - name: zookeeper
  #   run_list:
  #     - recipe[choonz-queue-service::zookeeper]
  #   verifier:
  #     inspec_tests:
  #       - test/smoke/zookeeper
  #   driver_config:
  #     instance_name: cqs-zookeeper
  # - name: kafka
  #   # run_list:
  #   #   - recipe[choonz-queue-service::kafka]
  #   verifier:
  #     inspec_tests:
  #       - test/smoke/kafka
  #   driver_config:
  #     disable_upstart: false
  #     links: cqs-zookeeper:zookeeper
  #     instance_name: cqs-kafka
  #     image: ches/kafka
  #     run_options: --env ZOOKEEPER_IP=zookeeper
