---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  product_name: chef
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: app
    run_list:
      - recipe[choonz-queue-service::app]
    verifier:
      inspec_tests:
        - test/smoke/app
    attributes:
